name: Build, Test, and Deploy

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright system dependencies
        run: npx playwright install-deps

      - name: Install additional webkit dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstreamer-ocaml-dev xvfb

      - name: Configure ALSA null device
        run: |
          mkdir -p ~/.config/alsa
          cat > ~/.config/alsa/asoundrc << EOF
          pcm.!default {
            type null
          }
          ctl.!default {
            type null
          }
          EOF

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test:run

      - name: Run e2e tests
        env:
          PULSE_SERVER: unix:/tmp/pulse-server
          DEBUG: pw:browser
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" npm run test:e2e

      - name: Build project
        run: npm run build

      - name: Upload artifact to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
